### ISSUE TITLE
websocket连不上

### ISSUE THREAD

**Issue by mengfanyin** [LBank-exchange/lbank-official-api-docs#1]
请问为什么 ws://api.lbank.info/ws 一直连不上？

**Comment by li-hu** [comment]
您好， 请问您连接不上这个问题解决了吗？ 怎么解决的？@mengfanyin

**Comment by mengfanyin** [comment]
咨询官方说这个ws服务暂时还没开通。@li-hu

**Comment by li-hu** [comment]
哦 好的  谢谢 @mengfanyin

**Comment by LBank-exchange** [comment]
请访问新版的web socket API
https://github.com/LBank-exchange/lbank-official-api-docs/blob/master/API-For-Spot-CN/币币交易Websocket%20API(行情).md
