### ISSUE TITLE
k线api接口问题

### ISSUE THREAD

**Issue by kevinwu199** [LBank-exchange/lbank-official-api-docs#5]
下面是time参数为8月3日
`http://api.lbank.info/v1/kline.do?symbol=dx_eth&type=minute1&size=2000&time=1533225600`

下面是time参数为8月8日
`http://api.lbank.info/v1/kline.do?symbol=dx_eth&type=minute1&size=2000&time=1533657600`

第一个api获取不到数据，但是第二个api可以获取数据，
正常应该使用8月3号能够获取8月3日以后的数据，
否则用户使用该api时，必须先知道你们那些时间点有数据才能获取

**Comment by LBank-exchange** [comment]
考虑增加一个API获取每个币对开始交易的时间，但该issue本身不会被修正。
