### ISSUE TITLE
Websocket getting a lot of pings but no actual data

### ISSUE THREAD

**Issue by cgebe** [LBank-exchange/lbank-official-api-docs#8]
I am subscribing with `"{"action": "subscribe", "subscribe": "tick", "pair": "<pair>"}"` , but i do not get any actual data!! 

I understand that the websocket API is titled as BETA, but its more of a pre-alpha

**Comment by GoChartingAdmin** [comment]
Same here.  Please suggest

**Comment by cgebe** [comment]
data is sent now, but please consider https://github.com/LBank-exchange/lbank-official-api-docs/issues/7

**Comment by GoChartingAdmin** [comment]
@mengfanyin

LBANK is now added to **[GoCharting](https://gocharting.com)** platform

![image](https://user-images.githubusercontent.com/20324844/44971570-6452db00-af56-11e8-9748-a8260eb66707.png)
